version: "3.2"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    ports:
      - '2182:2182'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - clickhouse-tier

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: topic:1:1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_RESTART_ATTEMPTS: 10
      KAFKA_RESTART_DELAY: 5
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
    healthcheck:
      test: nc -z 0.0.0.0 9092 || exit
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      - zookeeper
    networks:
      - clickhouse-tier

  clickhouse:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - IS_DEV=1
        - KAFKA_BROKER_LIST=kafka:9092
        - KAFKA_TOPIC_LIST=topic
        - KAFKA_GROUP_NAME=q_real_time_tx_processing_ch
    command: ['bash', 'entrypoint.sh']
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: 0.0.0.0
      CLICKHOUSE_DB: clickhouse
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    ports:
      - '8123:8123'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8123/ping || exit 1
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - clickhouse-tier

networks:
  clickhouse-tier: